# Generated by Django 5.2.5 on 2025-08-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='branch',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='course',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='request',
            name='semester',
            field=models.CharField(default='None', max_length=4),
        ),
        migrations.AddField(
            model_name='request',
            name='subject',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='finalpapers',
            name='paper',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='private_key',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='q_pattern',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='syllabus',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
