# Generated by Django 5.2.5 on 2025-08-27 13:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_request_branch_request_course_request_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='request',
            name='course',
        ),
        migrations.RemoveField(
            model_name='request',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='request',
            name='subject',
        ),
        migrations.AlterField(
            model_name='finalpapers',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to='final_papers/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='enc_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BinaryField(default=None, max_length=500), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='request',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='private_keys/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='q_pattern',
            field=models.FileField(blank=True, null=True, upload_to='q_patterns/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Uploaded', 'Uploaded'), ('Finalized', 'Finalized'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/'),
        ),
    ]
