# Generated by Django 5.2.5 on 2025-10-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_request_branch_remove_request_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcode',
            name='q_pattern',
            field=models.FileField(blank=True, null=True, upload_to='default_q_patterns/'),
        ),
        migrations.AddField(
            model_name='subjectcode',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='default_syllabus/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subject',
            field=models.CharField(choices=[('None', 'None'), ('Internet of Things', 'Internet of Things'), ('Parallel Computing', 'Parallel Computing'), ('Cryptography', 'Cryptography'), ('Big Data Analytics', 'Big Data Analytics')], default='None', max_length=30),
        ),
    ]
