# Generated by Django 5.2.5 on 2025-10-26 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_subjectcode_q_pattern_subjectcode_syllabus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcode',
            name='q_pattern',
            field=models.FileField(blank=True, null=True, upload_to='subject_qpatterns/'),
        ),
        migrations.AlterField(
            model_name='subjectcode',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='subject_syllabus/'),
        ),
        migrations.CreateModel(
            name='ScrutinyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('plagiarism_percentage', models.FloatField(default=0.0)),
                ('questions_analysis', models.JSONField(default=list, help_text='List of question analysis data')),
                ('bloom_distribution', models.JSONField(default=dict, help_text="Distribution of questions across Bloom's taxonomy levels")),
                ('difficulty_distribution', models.JSONField(default=dict, help_text='Distribution of questions by difficulty level')),
                ('duplicate_questions', models.JSONField(default=list, help_text='List of question pairs identified as duplicates')),
                ('topic_tags', models.JSONField(default=list, help_text='Topic tags extracted from questions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scrutiny', to='exams.request')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
