# Generated by Django 5.2.5 on 2025-10-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_subjectcode_q_pattern_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrutinyResult',
        ),
    ]
