# Generated by Django 5.2.5 on 2025-10-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_delete_scrutinyresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subject',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
